HADOOP_USER_NAME=hive /usr/bin/sqoop import \
  --connect jdbc:oracle:thin:@bootcamp-march2017.cghfmcr8k3ia.us-west-2.rds.amazonaws.com:15210:gravity \
  --username gravity \
  --password gravity \
  --table ADMIN.ASTROPHYSICISTS \
  --hive-import \
  --hive-database default  \
  --hive-table astro  \
  --map-column-hive ASTROPHYSICIST_ID=INT,ASTROPHYSICIST_NAME=STRING,YEAR_OF_BIRTH=STRING,NATIONALITY=STRING \
  --direct \
  -m 2 \
